name: logosapi
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['18.x']
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      name: Use Node.js ${{ matrix.node-version }}
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install and test
      run: |
        npm install
        npm test
        npm run update-logos
      env:
        CI: true
  build:
    runs-on: ubuntu-latest
    steps:
    - name: clone
      uses: actions/checkout@v3
    - name: build docker image
      run: docker build -t soulchild/logos-api .
    - name: log into docker hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: push to docker hub
      run: docker push soulchild/logos-api

